import { Resend } from 'resend';
const USD_TO_INR = Number(process.env.USD_TO_INR)
const resend = new Resend(process.env.RESEND_API_KEY);

export interface AuditEmailData {
  email: string;
  companyName?: string;
  auditId: string;
  totalMonthlySavings: number;
  totalAnnualSavings: number;
  auditUrl: string;
}

export async function sendAuditConfirmationEmail(data: AuditEmailData): Promise<boolean> {
  const isHighValue = data.totalMonthlySavings > 500 * USD_TO_INR;

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
                  color: white; padding: 30px; text-align: center; border-radius: 8px 8px 0 0; }
        .content { background: #f9fafb; padding: 30px; border-radius: 0 0 8px 8px; }
        .savings-box { background: white; border-left: 4px solid #10b981; 
                       padding: 20px; margin: 20px 0; border-radius: 4px; }
        .savings-amount { font-size: 32px; font-weight: bold; color: #10b981; }
        .button { display: inline-block; background: #667eea; color: white; 
                  padding: 12px 24px; text-decoration: none; border-radius: 6px; 
                  margin: 20px 0; }
        .footer { text-align: center; color: #6b7280; font-size: 14px; margin-top: 30px; }
        .high-value { background: #fef3c7; border-left-color: #f59e0b; padding: 15px; 
                      margin: 20px 0; border-radius: 4px; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>🎯 Your AI Spend Audit is Ready</h1>
          ${data.companyName ? `<p>Hi ${data.companyName}!</p>` : ''}
        </div>
        
        <div class="content">
          <p>Thanks for running your AI spend audit. Here's what we found:</p>
          
          <div class="savings-box">
            <h2>💰 Total Savings Potential</h2>
            <div class="savings-amount">₹${data.totalMonthlySavings.toLocaleString('en-IN')}/month</div>
            <p>₹${data.totalAnnualSavings.toLocaleString('en-IN')} saved per year</p>
          </div>

          ${isHighValue ? `
            <div class="high-value">
              <h3>🚀 High-Value Opportunity Detected</h3>
              <p>Your audit shows savings of over ₹${Math.ceil(500 * USD_TO_INR)}. Our team at Credex will reach out within 24 hours to help you capture these savings through our discounted AI credit marketplace.</p>
            </div>
          ` : `
            <p>You're doing well! For future optimization opportunities, we'll keep you posted when new tools or better plans become available.</p>
          `}

          <a href="${data.auditUrl}" class="button">View Full Audit Report</a>

          <p><strong>What's Next?</strong></p>
          <ul>
            <li>Review your personalized recommendations</li>
            <li>Implement the suggested changes</li>
            ${isHighValue ? '<li>Wait for Credex team to reach out with exclusive offers</li>' : ''}
          </ul>

          <div class="footer">
            <p>This audit was generated by AI Spend Audit</p>
            <p>Questions? Reply to this email or visit <a href="${data.auditUrl}">your audit page</a></p>
            <p style="font-size: 12px; margin-top: 20px;">
              You received this because you requested an AI spend audit at our website.
            </p>
          </div>
        </div>
      </div>
    </body>
    </html>
  `;

  const textContent = `
Your AI Spend Audit is Ready

Total Savings Potential: ₹${data.totalMonthlySavings.toLocaleString('en-IN')}/month
Annual Savings: ₹${data.totalAnnualSavings.toLocaleString('en-IN')}/year

${isHighValue ?
      'High-Value Opportunity: Your audit shows significant savings. Credex team will reach out within 24 hours.' :
      'You\'re spending well! We\'ll notify you of future optimization opportunities.'
    }

View your full report: ${data.auditUrl}

---
AI Spend Audit
Questions? Reply to this email.
  `;

  try {
    const { data: result, error } = await resend.emails.send({
      from: 'AI Spend Audit <onboarding@resend.dev>', // Use verified domain in production
      to: [data.email],
      subject: isHighValue
        ? `💰 You could save ₹${data.totalMonthlySavings.toLocaleString('en-IN')}/month on AI tools`
        : '✅ Your AI Spend Audit Results',
      html: htmlContent,
      text: textContent,
    });

    if (error) {
      console.error('Email send error:', error);
      return false;
    }

    console.log('Email sent successfully:', result);
    return true;
  } catch (error) {
    console.error('Email service error:', error);
    return false;
  }
}